PruebaMappeoDictionary/Models/ErrorViewModel.cs
using System;

namespace PruebaMappeoDictionary.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PruebaMappeoDictionary/Models/PruebaMappingDictionaryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace PruebaMappeoDictionary.Models
{
    public class PruebaMappingDictionaryViewModel
    {
        //Guid.NewGuid().ToString();
        public Dictionary<string, SubClassMappingDictionary> SubClassMappingDictionary { get; set; }
    }
    public class SubClassMappingDictionary
    {
        [Display(Name = "Propiedad")]
        public string StringProp { get; set; }
        public Dictionary<string, SubSubClassMappingDictionary> SubSubClassMappingDictionary { get; set; }
    }
    public class SubSubClassMappingDictionary
    {
        public string StrField { get; set; }
    }
}

PruebaMappeoDictionary/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PruebaMappeoDictionary.Models;

namespace PruebaMappeoDictionary.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PruebaMappeoDictionary/Controllers/PruebaMappingDictionaryController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using PruebaMappeoDictionary.Models;

namespace PruebaMappeoDictionary.Controllers
{
    public class PruebaMappingDictionaryController : Controller
    {
        public IActionResult Index()
        {
            PruebaMappingDictionaryViewModel vm = new PruebaMappingDictionaryViewModel
            {
                SubClassMappingDictionary = new System.Collections.Generic.Dictionary<string, SubClassMappingDictionary>
                {
                    { Guid.NewGuid().ToString(),
                        new SubClassMappingDictionary{
                            StringProp = "string prop",
                            SubSubClassMappingDictionary = new System.Collections.Generic.Dictionary<string, SubSubClassMappingDictionary>
                            {
                                { Guid.NewGuid().ToString(), new SubSubClassMappingDictionary{
                                    StrField = "Campo de texto 1"
                                } },
                                { Guid.NewGuid().ToString(), new SubSubClassMappingDictionary{
                                    StrField = "Campo de texto 2"
                                }
                                }
                            }
                        }
                    }
                }
            };
            return View(vm);
        }

        [HttpPost]
        public IActionResult Index(PruebaMappingDictionaryViewModel model)
        {
            return Json(model);
        }
    }
}

PruebaMappeoDictionary/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PruebaMappeoDictionary/Views/PruebaMappingDictionary/Index.cshtml
@using PruebaMappeoDictionary.Controllers;
@model PruebaMappingDictionaryViewModel;

<p>Hola</p>


@using (Html.BeginForm(FormMethod.Post))
{
    foreach (KeyValuePair<string, SubClassMappingDictionary> item in Model.SubClassMappingDictionary)
    {
        string currentKey = item.Key;
        @Html.EditorFor(m => Model.SubClassMappingDictionary[currentKey].StringProp)
        <p>Loop</p>
        <br />
        foreach(KeyValuePair<string, SubSubClassMappingDictionary> subitem in Model.SubClassMappingDictionary[currentKey].SubSubClassMappingDictionary)
        {
            string subitemCurrentKey = subitem.Key;
            @Html.EditorFor(m => Model.SubClassMappingDictionary[currentKey].SubSubClassMappingDictionary[subitemCurrentKey].StrField)
        }
    }
    <br />
    <button type="submit" class="btn btn-primary">Enviar</button>
}

PruebaMappeoDictionary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PruebaMappeoDictionary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PruebaMappeoDictionary</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PruebaMappingDictionary" asp-action="Index">Prueba Mapping Dictionary</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PruebaMappeoDictionary - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>